"""Vincio document engine: loaders, parsers, OCR, layout, multimodal, forms, audio."""

from .audio import (
    MockTranscriber,
    ProviderAudioTranscriber,
    Transcriber,
    Transcript,
    TranscriptSegment,
    WhisperTranscriber,
)
from .forms import (
    AzureDocumentAI,
    DocumentAI,
    FormField,
    GoogleDocumentAI,
    HeuristicFormExtractor,
    TextractDocumentAI,
    form_fields_to_evidence,
)
from .layout import (
    LayoutBlock,
    LayoutFigure,
    LayoutWord,
    PageLayout,
    assemble_layout,
    extract_pdf_layout,
    group_words_into_lines,
    order_blocks,
)
from .loaders import (
    SUPPORTED_EXTENSIONS,
    figure_evidence,
    load_directory,
    load_document,
    load_docx,
    load_media,
    load_pdf,
    load_video,
    load_xlsx,
    register_loader,
    supported_extensions,
)
from .multimodal import ImageAnalyzer, ImageObservation, image_evidence_items
from .ocr import OCREngine, TesseractOCR, VisionModelOCR
from .parsers import (
    CodeSymbol,
    Section,
    TableData,
    extract_code_symbols,
    extract_markdown_sections,
    extract_markdown_tables,
    infer_table_schema,
    parse_csv_table,
    parse_html,
    strip_html,
    structure_data,
    table_quality_checks,
)
from .registry import ParserRegistry, default_parser_registry
from .video import (
    FrameExtractor,
    MockVideoAnalyzer,
    ProviderVideoAnalyzer,
    PyAVFrameExtractor,
    VideoAnalysis,
    VideoAnalyzer,
    VideoFrame,
    VideoSegment,
    sample_frame_times,
    segment_timeline,
    video_evidence_items,
)

__all__ = [
    "SUPPORTED_EXTENSIONS",
    "load_directory",
    "load_document",
    "load_docx",
    "load_media",
    "load_pdf",
    "load_video",
    "load_xlsx",
    "figure_evidence",
    "register_loader",
    "supported_extensions",
    "ParserRegistry",
    "default_parser_registry",
    "ImageAnalyzer",
    "ImageObservation",
    "image_evidence_items",
    # video understanding
    "VideoFrame",
    "VideoSegment",
    "VideoAnalysis",
    "VideoAnalyzer",
    "MockVideoAnalyzer",
    "ProviderVideoAnalyzer",
    "FrameExtractor",
    "PyAVFrameExtractor",
    "sample_frame_times",
    "segment_timeline",
    "video_evidence_items",
    "LayoutWord",
    "LayoutBlock",
    "LayoutFigure",
    "PageLayout",
    "group_words_into_lines",
    "order_blocks",
    "assemble_layout",
    "extract_pdf_layout",
    "OCREngine",
    "TesseractOCR",
    "VisionModelOCR",
    # audio
    "Transcriber",
    "Transcript",
    "TranscriptSegment",
    "MockTranscriber",
    "WhisperTranscriber",
    "ProviderAudioTranscriber",
    # forms
    "DocumentAI",
    "FormField",
    "HeuristicFormExtractor",
    "TextractDocumentAI",
    "AzureDocumentAI",
    "GoogleDocumentAI",
    "form_fields_to_evidence",
    # parsers
    "CodeSymbol",
    "Section",
    "TableData",
    "extract_code_symbols",
    "extract_markdown_sections",
    "extract_markdown_tables",
    "infer_table_schema",
    "parse_csv_table",
    "parse_html",
    "structure_data",
    "strip_html",
    "table_quality_checks",
]
