"""Vincio optimization engine."""

from .budget_learning import BudgetLearner, LearnedAllocations
from .cache_tuning import (
    CacheAdvice,
    CacheTuningReport,
    analyze_ast_layout,
    analyze_prompt_cacheability,
    cache_hit_economics,
)
from .compression_tuning import CompressionTuner, CompressionTuningResult
from .context_search import ContextOptimizer, ContextSearchSpace
from .controller import ContinuousImprovementController, ControllerDecision
from .distill import (
    BootstrapFinetune,
    DistillationResult,
    TrainingExample,
    TrainingSet,
    export_training_set,
    export_training_set_from_runs,
    provider_trainer,
    semantic_dedupe,
)
from .judge_calibration import (
    JudgeCalibrationResult,
    JudgeCalibrator,
    JudgeStepProposal,
    JudgeStepReflector,
)
from .loop import (
    DEFAULT_LOOP_METRICS,
    ExperimentProposal,
    ExperimentProposer,
    ImprovementLoop,
    LoopResult,
)
from .pareto import (
    AGENTIC_OBJECTIVES,
    DEFAULT_OBJECTIVES,
    ObjectiveSpec,
    ParetoFrontier,
    ParetoPoint,
    ParetoResult,
    dominates,
    objective_vector,
    pareto_loop,
)
from .prompt_search import PromptOptimizer
from .reflective import (
    HeuristicReflector,
    LLMReflector,
    MIPROProposer,
    ProposedEdit,
    Reflection,
    ReflectiveOptimizer,
    ReflectiveResult,
    Reflector,
    apply_edits,
    cluster_failures,
)
from .retrieval_feedback import (
    ChunkingRecommendation,
    RelevanceRecord,
    RetrievalFeedback,
    RetrievalFeedbackResult,
    recommend_chunking,
    records_from_dataset,
    records_from_report,
)
from .routing import (
    BanditDecision,
    CascadeRung,
    EpsilonGreedyBandit,
    GuardedBanditRouter,
    LinUCB,
    ModelCascade,
    Router,
    RouteStrategy,
    RoutingDecision,
    RoutingOptimizer,
    RoutingPolicy,
    UCB1Bandit,
    estimate_difficulty,
    response_confidence,
)
from .search import Candidate, FitnessWeights, OptimizationResult, evolution_loop, fitness
from .self_improvement import (
    CanarySpec,
    CanaryVerdict,
    DeployResult,
    MetaSpec,
    SelfImprovementController,
    SelfImprovementEvent,
    SelfImprovementPolicy,
    deploy_candidate,
    learn_fitness_weights,
    select_for_labeling,
    successive_halving,
)
from .strategies import (
    AnnealingSearch,
    HillClimbSearch,
    RandomSearch,
    SearchStrategy,
    build_strategy,
    guided_search,
)

__all__ = [
    "BudgetLearner",
    "LearnedAllocations",
    "CacheAdvice",
    "CacheTuningReport",
    "analyze_ast_layout",
    "analyze_prompt_cacheability",
    "cache_hit_economics",
    "ContextOptimizer",
    "ContextSearchSpace",
    "CompressionTuner",
    "CompressionTuningResult",
    "TrainingExample",
    "TrainingSet",
    "export_training_set",
    "export_training_set_from_runs",
    "semantic_dedupe",
    "provider_trainer",
    "DistillationResult",
    "BootstrapFinetune",
    "ProposedEdit",
    "Reflection",
    "Reflector",
    "HeuristicReflector",
    "LLMReflector",
    "MIPROProposer",
    "ReflectiveOptimizer",
    "ReflectiveResult",
    "apply_edits",
    "cluster_failures",
    "JudgeStepProposal",
    "JudgeStepReflector",
    "JudgeCalibrationResult",
    "JudgeCalibrator",
    "DEFAULT_LOOP_METRICS",
    "ImprovementLoop",
    "LoopResult",
    "ContinuousImprovementController",
    "ControllerDecision",
    "ExperimentProposal",
    "ExperimentProposer",
    "SelfImprovementPolicy",
    "SelfImprovementController",
    "SelfImprovementEvent",
    "CanarySpec",
    "CanaryVerdict",
    "MetaSpec",
    "DeployResult",
    "deploy_candidate",
    "successive_halving",
    "learn_fitness_weights",
    "select_for_labeling",
    "DEFAULT_OBJECTIVES",
    "AGENTIC_OBJECTIVES",
    "ObjectiveSpec",
    "ParetoFrontier",
    "ParetoPoint",
    "ParetoResult",
    "dominates",
    "objective_vector",
    "pareto_loop",
    "PromptOptimizer",
    "ChunkingRecommendation",
    "RelevanceRecord",
    "RetrievalFeedback",
    "RetrievalFeedbackResult",
    "recommend_chunking",
    "records_from_dataset",
    "records_from_report",
    "EpsilonGreedyBandit",
    "RoutingOptimizer",
    "RoutingPolicy",
    "UCB1Bandit",
    "LinUCB",
    "GuardedBanditRouter",
    "BanditDecision",
    "estimate_difficulty",
    "CascadeRung",
    "ModelCascade",
    "response_confidence",
    "Router",
    "RoutingDecision",
    "RouteStrategy",
    "Candidate",
    "FitnessWeights",
    "OptimizationResult",
    "evolution_loop",
    "fitness",
    "AnnealingSearch",
    "HillClimbSearch",
    "RandomSearch",
    "SearchStrategy",
    "build_strategy",
    "guided_search",
]
