"""Vincio security: PII, secrets, injection defense, access, audit."""

from .access import (
    AccessController,
    AccessDecision,
    AccessRule,
    AllowListGate,
    Principal,
    Role,
)
from .audit import (
    AuditEntry,
    AuditLog,
    ChainVerification,
    RetentionPolicy,
    apply_retention,
    verify_audit_file,
)
from .backends import DetectorBackend, DetectorSpan
from .capability import (
    CapabilityBroker,
    CapabilityToken,
    CapabilityVerification,
    ContainmentEvent,
    ContainmentMonitor,
    ContainmentReport,
    TaintedValue,
    TrustLabel,
    requires_authority,
    verify_containment,
)
from .dualplane import DualPlaneExecutor, PlannedCall, QuarantineRef
from .identity import (
    AgentCredential,
    AgentIdentity,
    CredentialVerification,
    Delegation,
    DelegationChain,
    DelegationChainVerification,
    DelegationVerification,
    Grant,
    IdentityDocument,
    IdentityVerification,
    KeyAuthorization,
    KeyRecord,
    Keyring,
    SignatureCheck,
    did_from_public_key,
    is_vincio_did,
    key_fingerprint,
    public_key_from_did,
)
from .injection import InjectionDetector, InjectionVerdict, wrap_untrusted
from .locales import LocalePack, available_locales, get_locale_pack
from .pii import PIIDetector, PIIMatch, redact
from .poisoning import PoisoningDetector, PoisoningReport, PoisonSignal, PoisonVerdict
from .policy import PolicyCheckResult, PolicyEngine, PolicyViolation
from .rails import Rail, RailEngine
from .secrets import SecretFinding, SecretScanner, SecretString

__all__ = [
    "AccessController",
    "AccessDecision",
    "AccessRule",
    "AllowListGate",
    "Principal",
    "Role",
    "AuditEntry",
    "AuditLog",
    "ChainVerification",
    "RetentionPolicy",
    "apply_retention",
    "verify_audit_file",
    "InjectionDetector",
    "InjectionVerdict",
    "wrap_untrusted",
    "TrustLabel",
    "TaintedValue",
    "CapabilityToken",
    "CapabilityVerification",
    "CapabilityBroker",
    "ContainmentEvent",
    "ContainmentReport",
    "ContainmentMonitor",
    "verify_containment",
    "requires_authority",
    "DualPlaneExecutor",
    "QuarantineRef",
    "PlannedCall",
    # agent identity, delegation & cryptographic accountability
    "AgentIdentity",
    "IdentityDocument",
    "Keyring",
    "KeyRecord",
    "KeyAuthorization",
    "Grant",
    "Delegation",
    "DelegationChain",
    "AgentCredential",
    "IdentityVerification",
    "DelegationVerification",
    "DelegationChainVerification",
    "CredentialVerification",
    "SignatureCheck",
    "did_from_public_key",
    "public_key_from_did",
    "is_vincio_did",
    "key_fingerprint",
    "LocalePack",
    "available_locales",
    "get_locale_pack",
    "PIIDetector",
    "PIIMatch",
    "redact",
    "PoisoningDetector",
    "PoisoningReport",
    "PoisonSignal",
    "PoisonVerdict",
    "PolicyCheckResult",
    "PolicyEngine",
    "PolicyViolation",
    "Rail",
    "RailEngine",
    "SecretFinding",
    "SecretScanner",
    "SecretString",
    "DetectorBackend",
    "DetectorSpan",
]
