"""Shared plumbing for generated media: cost metering & provenance.

Image generation and speech synthesis are not token-priced, so they carry a
small per-asset price model here (overridable, like the text
:class:`~vincio.observability.costs.PriceTable`). Every generated asset is
metered against the run :class:`~vincio.core.types.Budget` at the same choke
point text is, and stamped with a media-aware C2PA manifest bound to its bytes —
the governance machinery finally reaching generated media.
"""

from __future__ import annotations

from ..core.errors import BudgetExceededError
from ..core.types import Budget, BudgetUsage
from ..governance.transparency import (
    ContentSigner,
    ProvenanceManifest,
    embed_provenance,
    mark_synthetic_content,
)

__all__ = [
    "ImagePrice",
    "SpeechPrice",
    "IMAGE_PRICES",
    "SPEECH_PRICES",
    "image_cost",
    "speech_cost",
    "meter_media_cost",
    "attach_media_provenance",
]


class ImagePrice:
    """Per-image USD price by quality tier (a coarse, overridable model)."""

    def __init__(self, *, low: float = 0.0, medium: float = 0.0, high: float = 0.0) -> None:
        self.low = low
        self.medium = medium
        self.high = high

    def per_image(self, quality: str) -> float:
        return {"low": self.low, "medium": self.medium, "high": self.high}.get(
            _quality_tier(quality), self.medium
        )


class SpeechPrice:
    """USD price per million characters of synthesized speech."""

    def __init__(self, *, per_mchar: float = 0.0) -> None:
        self.per_mchar = per_mchar


# Coarse public rates (USD), overridable per provider call. Kept conservative
# and explicit rather than silently billing $0 for an unknown model.
IMAGE_PRICES: dict[str, ImagePrice] = {
    "gpt-image-1": ImagePrice(low=0.011, medium=0.042, high=0.167),
    "dall-e-3": ImagePrice(low=0.04, medium=0.04, high=0.08),
    "imagen-3.0-generate-002": ImagePrice(low=0.03, medium=0.03, high=0.03),
    "imagen-4.0-generate-001": ImagePrice(low=0.04, medium=0.04, high=0.06),
    "mock-image": ImagePrice(low=0.0, medium=0.0, high=0.0),
}

SPEECH_PRICES: dict[str, SpeechPrice] = {
    "gpt-4o-mini-tts": SpeechPrice(per_mchar=12.0),
    "tts-1": SpeechPrice(per_mchar=15.0),
    "tts-1-hd": SpeechPrice(per_mchar=30.0),
    "gemini-2.5-flash-preview-tts": SpeechPrice(per_mchar=10.0),
    "eleven_multilingual_v2": SpeechPrice(per_mchar=110.0),
    "mock-tts": SpeechPrice(per_mchar=0.0),
}


def _quality_tier(quality: str) -> str:
    quality = (quality or "auto").lower()
    if quality in ("low", "standard"):
        return "low"
    if quality in ("high", "hd"):
        return "high"
    return "medium"


def image_cost(model: str, *, n: int, quality: str, price: ImagePrice | None = None) -> float:
    price = price or IMAGE_PRICES.get(model)
    if price is None:
        return 0.0
    return round(price.per_image(quality) * max(1, n), 8)


def speech_cost(model: str, *, characters: int, price: SpeechPrice | None = None) -> float:
    price = price or SPEECH_PRICES.get(model)
    if price is None:
        return 0.0
    return round(price.per_mchar * characters / 1_000_000, 8)


def meter_media_cost(
    cost_usd: float,
    *,
    budget: Budget | None,
    usage: BudgetUsage | None,
) -> None:
    """Add a media-generation cost to the run usage and enforce the cost cap.

    Mirrors text-run budget enforcement: a generated asset that would push the
    run past ``max_cost_usd`` raises :class:`BudgetExceededError` before the
    cost is committed downstream.
    """
    if usage is not None:
        usage.cost_usd += cost_usd
    if budget is not None and usage is not None and "cost_usd" in usage.exceeds(budget):
        raise BudgetExceededError(
            f"media generation cost ${usage.cost_usd:.4f} exceeds budget ${budget.max_cost_usd:.4f}",
            used=usage.cost_usd,
            limit=budget.max_cost_usd,
        )


def attach_media_provenance(
    data: bytes,
    *,
    media_type: str,
    model: str | None = None,
    provider: str | None = None,
    edited: bool = False,
    signer: ContentSigner | None = None,
    watermark_hook=None,
) -> tuple[bytes, ProvenanceManifest]:
    """Embed a media-aware C2PA manifest into generated bytes.

    Returns ``(bytes, manifest)``: the (possibly watermarked / metadata-embedded)
    bytes and the manifest re-bound to them, so the credential matches what a
    consumer receives.
    """
    manifest = mark_synthetic_content(
        data, model_id=model, provider=provider, media_type=media_type, edited=edited
    )
    stamped = embed_provenance(data, manifest, watermark_hook=watermark_hook)
    if stamped is not data:
        # Re-bind to the bytes the consumer will actually get.
        manifest = mark_synthetic_content(
            stamped, model_id=model, provider=provider, media_type=media_type, edited=edited,
            signer=signer,
        )
    elif signer is not None:
        manifest = mark_synthetic_content(
            data, model_id=model, provider=provider, media_type=media_type, edited=edited,
            signer=signer,
        )
    return stamped, manifest
