"""Vincio retrieval engine."""

from .chunking import CHUNKERS, chunk_document
from .embeddings import (
    BatchingEmbedder,
    CachedEmbedder,
    CohereEmbedder,
    CohereMultimodalEmbedder,
    Embedder,
    HTTPEmbedder,
    InputType,
    JinaEmbedder,
    LocalHashEmbedder,
    MatryoshkaEmbedder,
    MultimodalEmbedder,
    MultimodalInput,
    ProviderEmbedder,
    VoyageContextualEmbedder,
    VoyageEmbedder,
    VoyageMultimodalEmbedder,
    build_embedder,
    cosine,
    embed_texts,
    mrl_truncate,
)
from .engine import QueryPlan, RetrievalEngine, RetrievalResult, reciprocal_rank_fusion
from .filters import FilterSpec, and_, contains, eq, exists, in_, ne, not_, or_, range_
from .graph_retrieval import EntityGraph, GraphPath
from .graphrag import Community, GraphRAG, detect_communities
from .hierarchy import AutoMergingIndex, contextualize_chunks
from .indexes import (
    BM25Index,
    Index,
    SearchFilter,
    SearchHit,
    VectorIndex,
    Where,
    build_filter,
    build_filter_spec,
)
from .late_interaction import LateInteractionIndex
from .live import LiveIndex, UpsertStats
from .query_understanding import QUERY_STRATEGIES, QueryExpansion, QueryUnderstanding
from .reasoning_retrieval import FactCoverage, FactRequirement, FactSchema, ReasoningRetriever
from .rerankers import (
    AuthorityReranker,
    CohereReranker,
    CrossEncoderReranker,
    HeuristicReranker,
    HTTPReranker,
    JinaReranker,
    LLMReranker,
    RecencyReranker,
    Reranker,
    VoyageReranker,
    build_reranker,
)
from .sharded import ShardedIndex
from .sparse import CallableSparseEncoder, LocalImpactEncoder, SparseEncoder, SparseIndex

__all__ = [
    "CHUNKERS",
    "chunk_document",
    "CachedEmbedder",
    "BatchingEmbedder",
    "MatryoshkaEmbedder",
    "Embedder",
    "InputType",
    "LocalHashEmbedder",
    "ProviderEmbedder",
    "HTTPEmbedder",
    "JinaEmbedder",
    "VoyageEmbedder",
    "CohereEmbedder",
    "VoyageContextualEmbedder",
    "MultimodalInput",
    "MultimodalEmbedder",
    "VoyageMultimodalEmbedder",
    "CohereMultimodalEmbedder",
    "build_embedder",
    "embed_texts",
    "mrl_truncate",
    "cosine",
    "QueryPlan",
    "RetrievalEngine",
    "RetrievalResult",
    "reciprocal_rank_fusion",
    "EntityGraph",
    "GraphPath",
    "Community",
    "GraphRAG",
    "detect_communities",
    "AutoMergingIndex",
    "contextualize_chunks",
    "BM25Index",
    "Index",
    "SearchFilter",
    "SearchHit",
    "VectorIndex",
    "Where",
    "build_filter",
    "build_filter_spec",
    "FilterSpec",
    "and_",
    "or_",
    "not_",
    "eq",
    "ne",
    "in_",
    "range_",
    "exists",
    "contains",
    "LateInteractionIndex",
    "LiveIndex",
    "UpsertStats",
    "ShardedIndex",
    "QUERY_STRATEGIES",
    "QueryExpansion",
    "QueryUnderstanding",
    "FactCoverage",
    "FactRequirement",
    "FactSchema",
    "ReasoningRetriever",
    "AuthorityReranker",
    "CrossEncoderReranker",
    "HeuristicReranker",
    "LLMReranker",
    "RecencyReranker",
    "Reranker",
    "HTTPReranker",
    "CohereReranker",
    "JinaReranker",
    "VoyageReranker",
    "build_reranker",
    "CallableSparseEncoder",
    "LocalImpactEncoder",
    "SparseEncoder",
    "SparseIndex",
]
