"""Vincio: the context engineering platform for AI applications.

Compiles prompts, memory, retrieval, tools, schemas, and policies into
optimized, validated, observable, provider-neutral context packets.
"""

from .agents import (
    AgentRole,
    Blackboard,
    CalibrationReport,
    CostAwareSelector,
    Crew,
    DistributedCheckpointer,
    HTNDomain,
    ModelPredictivePlanner,
    MPCResult,
    MPCStep,
    PlanRepairer,
    PredictedStep,
    ReasoningController,
    ReasoningDecision,
    ReasoningPolicy,
    ResearchAgent,
    ResearchBudget,
    ResearchReport,
    ScheduleResult,
    Send,
    StateGraph,
    SubgraphScheduler,
    SubgraphTask,
    TimerService,
    Transition,
    WorkerPoolBackend,
    WorldModel,
    compose,
    record_transitions,
    sleep_for,
    sleep_until,
    task_goal_value,
    wait_for_event,
)
from .assistant import ApprovalRecord, Assistant, AssistantTurn
from .caching import (
    CalibrationExample,
    KVPrefixPool,
    LearnedSemanticCache,
    ReasoningTrace,
    ReasoningTraceCache,
    SemanticCacheGate,
    SemanticCachePolicy,
    SemanticGateCase,
    ThresholdCalibrator,
)
from .choreography import (
    BindingCandidate,
    BindingWeights,
    CapabilityBinder,
    Choreography,
    RemoteParticipant,
    Saga,
    SagaJournal,
    SagaResult,
    SagaStep,
    StepBinding,
    StepOutcome,
    StepRecord,
    StepRequest,
    choreography_a2a_server,
)
from .context.llmlingua import LLMLinguaCompressor
from .context.longhorizon import (
    ContextBudget,
    ContextCompactor,
    ContextGovernor,
    RelevanceDecay,
)
from .core.app import ContextApp, RunHandle
from .core.config import VincioConfig, load_config
from .core.errors import VincioError
from .core.types import (
    Budget,
    Constraint,
    EvidenceItem,
    Example,
    Instruction,
    MemoryItem,
    MemoryScope,
    MemoryType,
    Objective,
    PolicySet,
    RunConfig,
    RunResult,
    RunStreamEvent,
    TaskType,
    UserInput,
)
from .edge import (
    EdgeEnvironment,
    EdgeManifest,
    EdgeParityReport,
    EdgeProfile,
    EdgeRequest,
    EdgeResult,
    EdgeRuntime,
    edge_environment,
    edge_manifest,
    is_wasm_runtime,
    verify_edge_parity,
)
from .evals.adaptive import AdaptiveSampler
from .evals.attribution import CausalAttributor, attribute_regression
from .evals.benchmarks import BenchmarkAdapter, load_benchmark
from .evals.datasets import Dataset, GoldenRegressionSuite
from .evals.ensemble import JudgeEnsemble
from .evals.environment import (
    Environment,
    EnvironmentSimulator,
    ToolEnvironment,
    make_retail_environment,
)
from .evals.retrieval_eval import RetrievalEvaluator, RetrievalGoldenSet, retrieval_regression
from .evals.swap import SwapGate, SwapVerdict, model_swap_regression
from .generation import (
    CitationContract,
    CitedReportBuilder,
    DocumentArtifact,
    DocumentBuilder,
    DocumentContract,
    ImageGenRequest,
    ImageProvider,
    MockImageProvider,
    MockSpeechProvider,
    MockVideoProvider,
    SpeechProvider,
    SpeechRequest,
    VideoGenRequest,
    VideoProvider,
    generate_redline,
)
from .governance import (
    AIBOM,
    AnnexIVBuilder,
    ComplianceFramework,
    ComplianceReport,
    ConsentLedger,
    Counterexample,
    ErasureProof,
    ErasureResult,
    FertilityTracker,
    FRIAGenerator,
    GovernanceVerifier,
    Invariant,
    InvariantResult,
    LawfulBasis,
    LineageRecord,
    ModelCard,
    PrivacyAccountant,
    PrivacyBudget,
    PrivacyBudgetError,
    PrivacyDecision,
    PrivacyMechanism,
    PrivacyReport,
    PrivacySpend,
    ProvenanceManifest,
    Purpose,
    ResidencyPolicy,
    RiskTierClassifier,
    SystemCard,
    VerificationReport,
    verify_erasure_proof,
)
from .memory.engine import MemoryEngine, ScopedMemory
from .negotiation import (
    A2ANegotiator,
    Contract,
    ContractFulfillment,
    ContractTerms,
    ContractVerification,
    IssuePreference,
    Negotiation,
    NegotiationBudget,
    NegotiationPosition,
    NegotiationResult,
    Offer,
    buyer_position,
    negotiation_a2a_server,
    select_offer,
    seller_position,
)
from .notebook import enable_rich_reprs
from .observability.energy import (
    EnergyEstimate,
    EnergyIntensityTable,
    EnergyProfile,
)
from .observability.exporters import AlertSink, PrometheusExporter
from .observability.finops import (
    AlertManager,
    AlertRule,
    BudgetManager,
    CostBudget,
    CostLedger,
    EnergyBudget,
    EnergyReport,
)
from .observability.redaction import ContentCapturePolicy
from .observability.store import IndexedTraceStore
from .observability.viewer import serve_viewer
from .optimize.controller import ContinuousImprovementController, ControllerDecision
from .optimize.distill import BootstrapFinetune, TrainingSet, provider_trainer
from .optimize.federated import (
    Contribution,
    ContributionBuilder,
    FederatedImprovement,
    FederatedPolicy,
    FederatedRoundResult,
    FederatedSubspace,
    PrivacyConfig,
    SecureAggregator,
)
from .optimize.judge_calibration import JudgeCalibrator
from .optimize.local_adaptation import (
    AdaptationResult,
    AdaptedProvider,
    AdapterGate,
    AdapterRegistry,
    ContinualAdaptation,
    LocalAdaptationPolicy,
    LocalAdapter,
    LocalLoRATrainer,
)
from .optimize.loop import ExperimentProposer, ImprovementLoop, LoopResult
from .optimize.reflective import ReflectiveOptimizer
from .optimize.reputation import (
    MemberReputation,
    ReputationConfig,
    ReputationError,
    ReputationLedger,
    ReputationReport,
)
from .optimize.rewards import RewardModel, VerifiableReward
from .optimize.routing import GuardedBanditRouter, ModelCascade, Router
from .optimize.self_improvement import (
    CanarySpec,
    DeployResult,
    SelfImprovementController,
    SelfImprovementPolicy,
)
from .optimize.test_time import (
    JudgeVerifier,
    RewardVerifier,
    SearchBudget,
    SearchResult,
    TestTimeSearch,
    Verifier,
    VerifierScore,
)
from .optimize.trajectory_opt import (
    LearningResult,
    TrajectoryAdvantage,
    TrajectoryOptimizer,
)
from .output.routing import SchemaRouter
from .output.schemas import OutputContract, OutputSchema
from .packs import Pack, available_packs, load_pack
from .plugins import PluginInfo, discover_plugins, installed_plugins, load_plugins
from .prompts.signatures import InputField, OutputField, Predict, Signature, signature
from .prompts.templates import PromptSpec
from .providers import (
    BatchRunner,
    CanaryRouter,
    CircuitBreaker,
    GGUFProvider,
    HealthAwareFailover,
    KeyPool,
    LifecycleWatcher,
    ModelRegistry,
    OpenAIFineTuneBackend,
    ShadowProvider,
    default_model_registry,
    make_finetune_backend,
)
from .realtime import RealtimeSession, VoiceAgent
from .registry import AgentDirectory, BundleRecord, CommunityRegistry
from .retrieval import FastEmbedEmbedder, MatryoshkaEmbedder, ShardedIndex, TwoStageIndex
from .security.access import AllowListGate
from .security.capability import (
    CapabilityBroker,
    CapabilityToken,
    ContainmentMonitor,
    ContainmentReport,
    TaintedValue,
    TrustLabel,
    verify_containment,
)
from .security.dualplane import DualPlaneExecutor
from .security.poisoning import PoisoningDetector
from .security.rails import Rail
from .settlement import (
    AdmissionConfig,
    AdmissionDecision,
    AdmissionPolicy,
    AdmissionVerification,
    AttestationExchange,
    AttestationRevocation,
    CollateralPool,
    CollateralPoolVerification,
    Escrow,
    EscrowConfig,
    EscrowVerification,
    GatheredReputation,
    IssuerTrust,
    Meter,
    MeterReading,
    NettingSet,
    PooledContract,
    PortableReputation,
    Reconciliation,
    ReputationAttestation,
    ReputationBundle,
    Resolution,
    SettlementBook,
    SettlementRecord,
    SettlementReport,
    TrustConfig,
    TrustModel,
    UsageEvent,
    admit,
    arbitrate,
    attest_reputation,
    attestation_a2a_server,
    build_trust_model,
    combine_attestations,
    draw_pool,
    gather_reputation,
    net_books,
    net_settlements,
    post_collateral_pool,
    post_escrow,
    reconcile,
    revoke_attestation,
    settle_contract,
    settle_escrow,
    settle_saga,
)
from .stability import (
    API_VERSION,
    StabilityLevel,
    VincioDeprecationWarning,
    VincioExperimentalWarning,
    deprecated,
    experimental,
    stability_of,
)
from .workflows.engine import Workflow

__version__ = "3.35.0"

__all__ = [
    "ContextApp",
    "RunHandle",
    "Assistant",
    "AssistantTurn",
    "ApprovalRecord",
    "AgentRole",
    "Blackboard",
    "Crew",
    "ResearchAgent",
    "ResearchBudget",
    "ResearchReport",
    "StateGraph",
    "compose",
    "VincioConfig",
    "load_config",
    "VincioError",
    "Budget",
    "Constraint",
    "EvidenceItem",
    "Example",
    "Instruction",
    "MemoryItem",
    "MemoryScope",
    "MemoryType",
    "MemoryEngine",
    "ScopedMemory",
    "Objective",
    "PolicySet",
    "RunConfig",
    "RunResult",
    "RunStreamEvent",
    "TaskType",
    "UserInput",
    "Dataset",
    "ImprovementLoop",
    "LoopResult",
    "ContinuousImprovementController",
    "ControllerDecision",
    "ExperimentProposer",
    "SelfImprovementPolicy",
    "SelfImprovementController",
    "CanarySpec",
    "DeployResult",
    "GoldenRegressionSuite",
    "GuardedBanditRouter",
    "ReflectiveOptimizer",
    "TrainingSet",
    "BootstrapFinetune",
    "RewardModel",
    "VerifiableReward",
    "TrajectoryAdvantage",
    "TrajectoryOptimizer",
    "LearningResult",
    "TestTimeSearch",
    "Verifier",
    "VerifierScore",
    "JudgeVerifier",
    "RewardVerifier",
    "SearchBudget",
    "SearchResult",
    "ReasoningController",
    "ReasoningDecision",
    "ReasoningPolicy",
    "ReasoningTrace",
    "ReasoningTraceCache",
    # learned semantic cache & near-miss KV reuse
    "LearnedSemanticCache",
    "SemanticCachePolicy",
    "SemanticCacheGate",
    "SemanticGateCase",
    "ThresholdCalibrator",
    "CalibrationExample",
    "KVPrefixPool",
    # on-device fine-tuning & continual local adaptation
    "LocalAdapter",
    "LocalLoRATrainer",
    "AdaptedProvider",
    "AdapterRegistry",
    "AdapterGate",
    "LocalAdaptationPolicy",
    "AdaptationResult",
    "ContinualAdaptation",
    # federated / cross-org self-improvement
    "PrivacyConfig",
    "Contribution",
    "ContributionBuilder",
    "FederatedSubspace",
    "SecureAggregator",
    "FederatedPolicy",
    "FederatedRoundResult",
    "FederatedImprovement",
    # cross-fleet reputation & weighting
    "ReputationLedger",
    "ReputationConfig",
    "MemberReputation",
    "ReputationReport",
    "ReputationError",
    # agent negotiation & contracting
    "Negotiation",
    "NegotiationResult",
    "NegotiationBudget",
    "NegotiationPosition",
    "IssuePreference",
    "Offer",
    "Contract",
    "ContractTerms",
    "ContractVerification",
    "ContractFulfillment",
    "A2ANegotiator",
    "negotiation_a2a_server",
    "select_offer",
    "buyer_position",
    "seller_position",
    # cross-org workflow choreography
    "Saga",
    "SagaStep",
    "SagaResult",
    "SagaJournal",
    "StepRecord",
    "StepRequest",
    "StepOutcome",
    "Choreography",
    "RemoteParticipant",
    "choreography_a2a_server",
    # cross-org workflow discovery & dynamic choreography
    "CapabilityBinder",
    "BindingWeights",
    "BindingCandidate",
    "StepBinding",
    # agent-to-agent settlement & metering
    "Meter",
    "MeterReading",
    "UsageEvent",
    "SettlementRecord",
    "SettlementBook",
    "SettlementReport",
    "Reconciliation",
    "reconcile",
    "settle_contract",
    "settle_saga",
    # cross-org settlement netting & multilateral clearing
    "NettingSet",
    "net_settlements",
    "net_books",
    # cross-org dispute resolution & arbitration
    "Resolution",
    "arbitrate",
    # cross-org reputation attestation & portability
    "ReputationAttestation",
    "AttestationRevocation",
    "PortableReputation",
    "attest_reputation",
    "revoke_attestation",
    "combine_attestations",
    # cross-org transitive trust & Sybil-resistant weighting
    "TrustConfig",
    "TrustModel",
    "IssuerTrust",
    "build_trust_model",
    # cross-org reputation gossip & attestation exchange
    "ReputationBundle",
    "GatheredReputation",
    "AttestationExchange",
    "attestation_a2a_server",
    "gather_reputation",
    # cross-org reputation-gated admission & progressive exposure
    "AdmissionConfig",
    "AdmissionDecision",
    "AdmissionVerification",
    "AdmissionPolicy",
    "admit",
    # cross-org collateralized settlement & escrow
    "Escrow",
    "EscrowConfig",
    "EscrowVerification",
    "post_escrow",
    "settle_escrow",
    # cross-org collateral pooling & cross-contract margin
    "CollateralPool",
    "CollateralPoolVerification",
    "PooledContract",
    "post_collateral_pool",
    "draw_pool",
    # world-model / simulation-based planning
    "WorldModel",
    "Transition",
    "PredictedStep",
    "CalibrationReport",
    "ModelPredictivePlanner",
    "MPCStep",
    "MPCResult",
    "record_transitions",
    "task_goal_value",
    "LLMLinguaCompressor",
    # long-horizon context engineering
    "ContextGovernor",
    "ContextCompactor",
    "ContextBudget",
    "RelevanceDecay",
    "JudgeCalibrator",
    "OutputContract",
    "OutputSchema",
    "SchemaRouter",
    "PromptSpec",
    "Signature",
    "InputField",
    "OutputField",
    "signature",
    "Predict",
    "Rail",
    # provable injection containment & capability-secure agents
    "TrustLabel",
    "TaintedValue",
    "CapabilityToken",
    "CapabilityBroker",
    "DualPlaneExecutor",
    "ContainmentMonitor",
    "ContainmentReport",
    "verify_containment",
    "Workflow",
    "Pack",
    "load_pack",
    "available_packs",
    "PluginInfo",
    "discover_plugins",
    "installed_plugins",
    "load_plugins",
    "enable_rich_reprs",
    "BatchRunner",
    "CircuitBreaker",
    "HealthAwareFailover",
    "KeyPool",
    "ModelRegistry",
    "default_model_registry",
    "ModelCascade",
    # provider/model rotation & swap regression
    "Router",
    "SwapGate",
    "SwapVerdict",
    "model_swap_regression",
    "ShadowProvider",
    "CanaryRouter",
    "LifecycleWatcher",
    "CostLedger",
    "CostBudget",
    "BudgetManager",
    # energy & carbon accounting
    "EnergyProfile",
    "EnergyEstimate",
    "EnergyIntensityTable",
    "EnergyBudget",
    "EnergyReport",
    # edge / WASM in-process runtime
    "EdgeRuntime",
    "EdgeRequest",
    "EdgeResult",
    "EdgeProfile",
    "EdgeEnvironment",
    "EdgeManifest",
    "EdgeParityReport",
    "edge_environment",
    "is_wasm_runtime",
    "edge_manifest",
    "verify_edge_parity",
    "ShardedIndex",
    "MatryoshkaEmbedder",
    "RealtimeSession",
    "VoiceAgent",
    "ModelCard",
    "SystemCard",
    "ComplianceReport",
    "ComplianceFramework",
    "AIBOM",
    "ResidencyPolicy",
    "LineageRecord",
    "ErasureResult",
    "ErasureProof",
    "verify_erasure_proof",
    "ConsentLedger",
    "Purpose",
    "LawfulBasis",
    # differential-privacy memory & training
    "PrivacyAccountant",
    "PrivacyBudget",
    "PrivacyMechanism",
    "PrivacySpend",
    "PrivacyDecision",
    "PrivacyReport",
    "PrivacyBudgetError",
    # formal verification of governance invariants
    "GovernanceVerifier",
    "VerificationReport",
    "InvariantResult",
    "Counterexample",
    "Invariant",
    "ProvenanceManifest",
    "FertilityTracker",
    "PoisoningDetector",
    # documents & images flow OUT
    "DocumentBuilder",
    "DocumentContract",
    "DocumentArtifact",
    "CitedReportBuilder",
    "CitationContract",
    "generate_redline",
    "ImageProvider",
    "ImageGenRequest",
    "MockImageProvider",
    "SpeechProvider",
    "SpeechRequest",
    "MockSpeechProvider",
    "VideoProvider",
    "VideoGenRequest",
    "MockVideoProvider",
    "RiskTierClassifier",
    "AnnexIVBuilder",
    "FRIAGenerator",
    # orchestrator & planner depth
    "HTNDomain",
    "PlanRepairer",
    "CostAwareSelector",
    "SubgraphScheduler",
    "SubgraphTask",
    "ScheduleResult",
    "TimerService",
    "sleep_until",
    "sleep_for",
    "wait_for_event",
    # scale out & train for real
    "WorkerPoolBackend",
    "DistributedCheckpointer",
    "Send",
    "provider_trainer",
    "OpenAIFineTuneBackend",
    "make_finetune_backend",
    "GGUFProvider",
    "IndexedTraceStore",
    "AlertManager",
    "AlertRule",
    "AlertSink",
    "PrometheusExporter",
    "ContentCapturePolicy",
    "serve_viewer",
    "TwoStageIndex",
    "FastEmbedEmbedder",
    # environment eval, benchmarks, retrieval eval, agent fabric
    "Environment",
    "ToolEnvironment",
    "EnvironmentSimulator",
    "make_retail_environment",
    "BenchmarkAdapter",
    "load_benchmark",
    # evaluation & quality frontier
    "JudgeEnsemble",
    "CausalAttributor",
    "attribute_regression",
    "AdaptiveSampler",
    "RetrievalEvaluator",
    "RetrievalGoldenSet",
    "retrieval_regression",
    "AgentDirectory",
    "CommunityRegistry",
    "BundleRecord",
    "AllowListGate",
    "API_VERSION",
    "StabilityLevel",
    "VincioDeprecationWarning",
    "VincioExperimentalWarning",
    "deprecated",
    "experimental",
    "stability_of",
    "__version__",
]
